const authRoutes = require('./auth');
const usersRoutes = require('./users');
const categoryRoutes = require("./category");
const contractsRoutes = require('./contracts');
const jobsRoutes = require('./jobs');
const schedulesRoutes = require('./schedules');
const offersRoutes = require('./offers');
const invoiceRoutes = require('./invoices');
const notificationsRoutes = require('./notifications');
const paymentsRoutes = require('./payments');
const feedbackRoutes = require('./feedback');
const favoritesRoutes = require('./favorites');
const invitesRoutes = require('./invites');
const chatsRoutes = require('./chats');
const adminRoutes = require('./admin');
const worktimesRoutes = require('./worktimes');
const subscriptionsRoutes = require('./subscriptions');
const mailRoutes = require('./mail');
const reportsRoutes = require('./reports');

module.exports = (router) => {
    authRoutes(router);
    usersRoutes(router);
    categoryRoutes(router);
    jobsRoutes(router);
    schedulesRoutes(router);
    invitesRoutes(router);
    offersRoutes(router);
    invoiceRoutes(router);
    notificationsRoutes(router);
    paymentsRoutes(router);
    feedbackRoutes(router);
    favoritesRoutes(router);
    chatsRoutes(router);
    adminRoutes(router);
    contractsRoutes(router);
    worktimesRoutes(router);
    subscriptionsRoutes(router);
    mailRoutes(router);
    reportsRoutes(router);
};
